"""Shared scaffold-state classification — the single home for spec 063's
"is this project scaffolded, adoptable, or greenfield?" decision.

Slice 063-01 (classify-and-route-on-new). Contract: spec 063
(scaffold-precondition-gate); doctrine ADR-0011 / ADR-0013 (a
route-don't-block deliberateness gate, not human-only enforcement).

`workflow.py new` (`reserve_spec`) is the one spec-creation door that today
improvises structure on an unscaffolded project. It consumes
`classify_scaffold_state` to route a `greenfield` project to
`/jig:scaffold-init` and an `adoptable` one to `/jig:migrate`, while a
`scaffolded` project reserves exactly as it does today.

What this module owns:
  - `classify_scaffold_state(project_dir) -> "scaffolded" | "adoptable" |
    "greenfield"` — the three-way, scaffold.json-FIRST classifier. The
    ordering is load-bearing (see the function docstring).
  - `looks_spec_driven(project_dir) -> bool` — the shared >=3-of-4 trigger
    predicate the classifier consumes (ADR-0002 rule-of-three: the third
    consumer of trigger-counting). The two TUNED call sites —
    scaffold-init's `_looks_already_spec_driven` and migrate's
    `compute_verdict` — are deliberately NOT retrofitted here (spec 063
    non-goals: they have intentionally different semantics, and rewriting
    them is a separate behavior-change risk). This module therefore
    transiently duplicates scaffold-init's empty-dir-counting variant.
  - `precondition_enabled()` — the `JIG_SCAFFOLD_PRECONDITION` bypass,
    mirroring `review_evidence.evidence_gate_enabled()` (same
    `{0,false,off,no}` vocabulary). Default = ON.

`_common` is a LEAF: this module imports only stdlib + the shared
`GATE_DISABLE_VALUES` vocabulary from `_common.review_evidence`. It does
NOT import from `skills/scaffold-init/` or any non-`_common` module.
"""

from __future__ import annotations

import os
from pathlib import Path

# Reuse the single bypass vocabulary so the spec-precondition gate and the
# review-evidence gate can never drift on what "disabled" means
# ({0,false,off,no}, case-insensitive). ADR-0011: an in-process gate is a
# deliberateness signal, not human-only enforcement, so an env escape hatch
# is consistent (cf. `JIG_REVIEW_EVIDENCE_GATE` / `JIG_CONVENTIONS_APPROVED`).
from _common.review_evidence import GATE_DISABLE_VALUES

# Watermark embedded in jig's scaffolded CLAUDE.md template. Its presence
# with `scaffold.json` ABSENT is the interrupted-scaffold case (a crashed
# mid-scaffold): we classify that as `greenfield` so the user re-runs
# scaffold-init recovery rather than being mis-routed to migrate. This
# literal mirrors scaffold-init's `_JIG_CLAUDE_MD_WATERMARK` — kept here as a
# constant rather than imported, because `_common` must stay a leaf (it must
# not depend on `skills/scaffold-init/`).
_JIG_CLAUDE_MD_WATERMARK = "Generated by [jig]"

# The completion sentinel: written LAST by scaffold-init (spec 032-02) at the
# project root. Its presence means "scaffolding finished" — covers in-repo,
# --plugin-only, and migrate-copied projects (which also carry a manifest).
_SCAFFOLD_SENTINEL = "scaffold.json"

# Environment variable that disables the spec-creation precondition.
PRECONDITION_ENV = "JIG_SCAFFOLD_PRECONDITION"


def precondition_enabled() -> bool:
    """The scaffold-precondition gate is enabled unless
    `JIG_SCAFFOLD_PRECONDITION` is set to one of the falsey tokens
    (`0`/`false`/`off`/`no`, case-insensitive). Default = ON.

    Mirrors `review_evidence.evidence_gate_enabled()` exactly (shared
    `GATE_DISABLE_VALUES`) — both are the same ADR-0011 deliberateness
    signal."""
    raw = os.environ.get(PRECONDITION_ENV)
    if raw is None:
        return True
    return raw.strip().lower() not in GATE_DISABLE_VALUES


def looks_spec_driven(project_dir: Path) -> bool:
    """Return True iff `project_dir` already has a spec-driven layout —
    >=3 of the four trigger categories present.

    The four categories (empty dirs DO count, mirroring scaffold-init's
    `_looks_already_spec_driven` semantics — the safer side errs toward
    routing-to-migrate before any tree is polluted):
      1. `docs/specs/` OR `docs/slices/` is a dir
      2. `docs/decisions/` OR `docs/adrs/` is a dir
      3. `docs/workflow.md` is a file
      4. `docs/architecture.md` is a file

    This is the shared predicate `classify_scaffold_state` consumes — the
    single copy of trigger-counting in the spec-precondition code (ADR-0002
    rule-of-three). The two TUNED call sites are NOT retrofitted (spec 063
    non-goals)."""
    docs = project_dir / "docs"
    count = 0
    # 1. spec-or-slice dir
    if (docs / "specs").is_dir() or (docs / "slices").is_dir():
        count += 1
    # 2. decisions-or-adrs dir
    if (docs / "decisions").is_dir() or (docs / "adrs").is_dir():
        count += 1
    # 3. workflow doc
    if (docs / "workflow.md").is_file():
        count += 1
    # 4. architecture doc
    if (docs / "architecture.md").is_file():
        count += 1
    return count >= 3


def _is_interrupted_scaffold(project_dir: Path) -> bool:
    """Return True iff `project_dir` looks like a previously-interrupted jig
    scaffold: a CLAUDE.md carrying the jig watermark, with `scaffold.json`
    absent (the absence is the caller's precondition — see
    `classify_scaffold_state`).

    Reads CLAUDE.md best-effort — any `OSError` returns False (treat as NOT
    partial, i.e. fall through to the trigger predicate). Mirrors
    scaffold-init's `_is_jig_partial_state` best-effort read."""
    claude_md = project_dir / "CLAUDE.md"
    if not claude_md.is_file():
        return False
    try:
        return _JIG_CLAUDE_MD_WATERMARK in claude_md.read_text()
    except OSError:
        return False


def classify_scaffold_state(project_dir: Path) -> str:
    """Classify `project_dir` as exactly one of `"scaffolded"` /
    `"adoptable"` / `"greenfield"`.

    The ordering is LOAD-BEARING — implement exactly this sequence:

      1. `scaffold.json` is a file at the root → `"scaffolded"`. It is THE
         completion sentinel (written last, spec 032-02); checked first so a
         finished project never re-routes.
      2. Else if the interrupted-scaffold case holds (jig CLAUDE.md
         watermark present, `scaffold.json` absent) → `"greenfield"` (route
         to scaffold-init RECOVERY, not migrate). This MUST come before the
         trigger predicate: a crashed scaffold can leave >=3 trigger dirs
         and would otherwise misclassify as `adoptable`.
      3. Else if the >=3-of-4 trigger predicate fires → `"adoptable"`.
      4. Else → `"greenfield"`.
    """
    if (project_dir / _SCAFFOLD_SENTINEL).is_file():
        return "scaffolded"
    # scaffold.json is absent below this line.
    if _is_interrupted_scaffold(project_dir):
        return "greenfield"
    if looks_spec_driven(project_dir):
        return "adoptable"
    return "greenfield"
