"""Tests for the shared scaffold-state classifier (slice 063-01).

`skills/_common/scaffold_state.py` is the single home for spec 063's
three-way scaffold-state classification — `scaffolded` / `adoptable` /
`greenfield` — and the shared >=3-of-4 trigger predicate the classifier
consumes (ADR-0002 rule-of-three: scaffold-init and migrate are the two
tuned call sites that are deliberately NOT retrofitted here).

Run from the repo root:
    python3 skills/_common/test_scaffold_state.py
"""

import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "skills"))

from _common import scaffold_state  # noqa: E402

# The watermark embedded in jig's scaffolded CLAUDE.md — its presence with
# scaffold.json absent is the interrupted-scaffold case. Mirrors
# scaffold-init's `_JIG_CLAUDE_MD_WATERMARK` (deliberately not imported —
# `_common` must stay a leaf; we assert the literal jig watermark string).
JIG_WATERMARK = "Generated by [jig]"


def _touch(path: Path, content: str = "x\n") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


class TriggerPredicateTests(unittest.TestCase):
    """AC5: the >=3-of-4 trigger logic lives in exactly one place and the
    classifier consumes it. Empty spec/slice dirs DO count (scaffold-init
    semantics)."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="jig-ss-trig-")
        self.target = Path(self.tmpdir)

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_predicate_is_exposed_as_named_function(self):
        # AC5: the predicate is a named function in the module (so there is
        # exactly one copy of the trigger logic in the new code).
        self.assertTrue(hasattr(scaffold_state, "looks_spec_driven"))
        self.assertTrue(callable(scaffold_state.looks_spec_driven))

    def test_zero_triggers_not_spec_driven(self):
        self.assertFalse(scaffold_state.looks_spec_driven(self.target))

    def test_two_triggers_not_spec_driven(self):
        (self.target / "docs" / "specs").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        self.assertFalse(scaffold_state.looks_spec_driven(self.target))

    def test_three_triggers_is_spec_driven(self):
        (self.target / "docs" / "specs").mkdir(parents=True)
        (self.target / "docs" / "decisions").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        self.assertTrue(scaffold_state.looks_spec_driven(self.target))

    def test_empty_spec_dir_counts_as_trigger(self):
        # scaffold-init semantics: empty docs/specs/ + docs/slices/ count.
        (self.target / "docs" / "specs").mkdir(parents=True)
        (self.target / "docs" / "adrs").mkdir(parents=True)
        _touch(self.target / "docs" / "architecture.md")
        self.assertTrue(scaffold_state.looks_spec_driven(self.target))

    def test_alias_dirs_count(self):
        # docs/slices/ aliases docs/specs/; docs/adrs/ aliases docs/decisions/.
        (self.target / "docs" / "slices").mkdir(parents=True)
        (self.target / "docs" / "adrs").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        _touch(self.target / "docs" / "architecture.md")
        self.assertTrue(scaffold_state.looks_spec_driven(self.target))


class ClassifyScaffoldStateTests(unittest.TestCase):
    """AC1: `classify_scaffold_state` is scaffold.json-first, then the
    >=3-of-4 predicate (adoptable), else greenfield — with the
    interrupted-scaffold case classifying as greenfield."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="jig-ss-classify-")
        self.target = Path(self.tmpdir)
        # Ensure no stray bypass env var leaks into classification (the
        # classifier itself is bypass-agnostic, but be defensive).
        self._saved = os.environ.pop("JIG_SCAFFOLD_PRECONDITION", None)

    def tearDown(self):
        if self._saved is not None:
            os.environ["JIG_SCAFFOLD_PRECONDITION"] = self._saved
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    # --- scaffolded ---------------------------------------------------
    def test_scaffold_json_present_is_scaffolded(self):
        _touch(self.target / "scaffold.json", "{}\n")
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "scaffolded",
        )

    def test_scaffold_json_wins_even_with_triggers(self):
        # scaffold.json is checked FIRST — a scaffolded project that also
        # has the full spec-driven layout is still "scaffolded".
        _touch(self.target / "scaffold.json", "{}\n")
        (self.target / "docs" / "specs").mkdir(parents=True)
        (self.target / "docs" / "decisions").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        _touch(self.target / "docs" / "architecture.md")
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "scaffolded",
        )

    def test_scaffold_json_must_be_a_file_not_a_dir(self):
        # A directory named scaffold.json is not the sentinel.
        (self.target / "scaffold.json").mkdir()
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "greenfield",
        )

    # --- adoptable ----------------------------------------------------
    def test_three_triggers_no_sentinel_is_adoptable(self):
        (self.target / "docs" / "specs").mkdir(parents=True)
        (self.target / "docs" / "decisions").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "adoptable",
        )

    # --- greenfield ---------------------------------------------------
    def test_empty_dir_is_greenfield(self):
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "greenfield",
        )

    def test_two_triggers_no_sentinel_is_greenfield(self):
        (self.target / "docs" / "specs").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "greenfield",
        )

    # --- interrupted-scaffold (the load-bearing ordering subtlety) ----
    def test_interrupted_scaffold_is_greenfield(self):
        # jig CLAUDE.md watermark, scaffold.json absent → greenfield
        # (route to scaffold-init RECOVERY, not migrate).
        _touch(self.target / "CLAUDE.md",
               f"# Project\n\n<!-- {JIG_WATERMARK} -->\n")
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "greenfield",
        )

    def test_interrupted_scaffold_with_three_triggers_still_greenfield(self):
        # THE ordering subtlety: a crashed scaffold can leave >=3 trigger
        # dirs AND the jig watermark. The interrupted-scaffold check MUST
        # run before the trigger predicate, so this is greenfield (recovery)
        # not adoptable (migrate).
        _touch(self.target / "CLAUDE.md",
               f"# Project\n\n<!-- {JIG_WATERMARK} -->\n")
        (self.target / "docs" / "specs").mkdir(parents=True)
        (self.target / "docs" / "decisions").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        _touch(self.target / "docs" / "architecture.md")
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "greenfield",
        )

    def test_non_jig_claude_md_with_three_triggers_is_adoptable(self):
        # A user's own CLAUDE.md (no jig watermark) does NOT trigger the
        # interrupted-scaffold short-circuit; with >=3 triggers it falls to
        # adoptable.
        _touch(self.target / "CLAUDE.md", "# My project\n")
        (self.target / "docs" / "specs").mkdir(parents=True)
        (self.target / "docs" / "decisions").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "adoptable",
        )

    def test_unreadable_claude_md_falls_through(self):
        # CLAUDE.md is read best-effort: an OSError → treat as NOT partial
        # (fall through to the trigger predicate). Simulate with a directory
        # named CLAUDE.md, which raises OSError on read_text.
        (self.target / "CLAUDE.md").mkdir()
        (self.target / "docs" / "specs").mkdir(parents=True)
        (self.target / "docs" / "decisions").mkdir(parents=True)
        _touch(self.target / "docs" / "workflow.md")
        # Not partial (read failed) → falls through to >=3 triggers →
        # adoptable.
        self.assertEqual(
            scaffold_state.classify_scaffold_state(self.target),
            "adoptable",
        )


class BypassTests(unittest.TestCase):
    """AC6: `JIG_SCAFFOLD_PRECONDITION` honors the {0,false,off,no}
    vocabulary (the shared `_common.parsing.ENV_FALSEY`, via
    `env_gate_enabled`). Default ON."""

    def setUp(self):
        self._saved = os.environ.pop("JIG_SCAFFOLD_PRECONDITION", None)

    def tearDown(self):
        if self._saved is not None:
            os.environ["JIG_SCAFFOLD_PRECONDITION"] = self._saved
        else:
            os.environ.pop("JIG_SCAFFOLD_PRECONDITION", None)

    def test_default_unset_gate_enabled(self):
        self.assertTrue(scaffold_state.precondition_enabled())

    def test_falsey_tokens_disable(self):
        for tok in ("0", "false", "off", "no", "FALSE", " Off ", "No"):
            os.environ["JIG_SCAFFOLD_PRECONDITION"] = tok
            self.assertFalse(
                scaffold_state.precondition_enabled(),
                f"token {tok!r} should disable the gate",
            )

    def test_truthy_tokens_keep_enabled(self):
        for tok in ("1", "true", "on", "yes", "anything"):
            os.environ["JIG_SCAFFOLD_PRECONDITION"] = tok
            self.assertTrue(
                scaffold_state.precondition_enabled(),
                f"token {tok!r} should keep the gate on",
            )


class WatermarkDriftGuardTests(unittest.TestCase):
    """Pin the interrupted-scaffold watermark to scaffold-init's source.

    `scaffold_state._JIG_CLAUDE_MD_WATERMARK` is a deliberate local copy of
    scaffold-init's `_JIG_CLAUDE_MD_WATERMARK` (kept here so `_common` stays a
    leaf — see the module docstring). That copy is load-bearing:
    interrupted-scaffold detection (-> route to scaffold-init recovery) only
    works if the literal matches the string scaffold-init's CLAUDE.md template
    actually emits. This guard fails if the two ever drift — mirroring spec
    050's people.md byte-identity cross-check. Source-text assertion (not an
    import) per the `test_atomic_io_sweep.py` pattern, since `scaffold-init`
    is not an importable module name (hyphen)."""

    def test_watermark_matches_scaffold_init_source(self):
        scaffold_src = (
            REPO_ROOT / "skills" / "scaffold-init" / "scaffold.py"
        ).read_text()
        expected = (
            f'_JIG_CLAUDE_MD_WATERMARK = "'
            f'{scaffold_state._JIG_CLAUDE_MD_WATERMARK}"'
        )
        self.assertIn(
            expected, scaffold_src,
            "scaffold_state._JIG_CLAUDE_MD_WATERMARK has drifted from "
            "scaffold-init's _JIG_CLAUDE_MD_WATERMARK — interrupted-scaffold "
            "detection would silently break. Keep the two literals identical.",
        )


class JigSelfHostDogfoodTests(unittest.TestCase):
    """Dogfood invariant: the jig repo itself must classify as `scaffolded`.

    jig is the plugin SOURCE — self-hosting and spec-driven, but it was never
    produced by scaffold-init (it IS scaffold-init). Spec 063's classifier
    treats "spec-driven layout + no scaffold.json" as `adoptable`
    (-> route to /jig:migrate). Without the completion sentinel, jig
    self-classifies `adoptable` and `workflow.py new` REFUSES in the jig repo —
    breaking jig's own spec reservation. That regression actually shipped (063
    fixtures all carried scaffold.json; nothing pinned the real repo), and this
    test is the guard so it can't recur: jig carries a real root `scaffold.json`
    (dogfooding the sentinel it asks every project to have), so it classifies
    `scaffolded` and `new` proceeds. See the spec-063 amendment.

    Runs only in the jig source repo (test_*.py is not copied into scaffolded
    targets), so REPO_ROOT is always the jig repo root."""

    def test_jig_repo_root_has_scaffold_json(self):
        self.assertTrue(
            (REPO_ROOT / "scaffold.json").is_file(),
            "jig repo root must carry a scaffold.json (the completion "
            "sentinel) so it self-classifies as scaffolded — without it, "
            "`workflow.py new` refuses in the jig repo (spec 063 regression).",
        )

    def test_jig_repo_root_classifies_scaffolded(self):
        self.assertEqual(
            scaffold_state.classify_scaffold_state(REPO_ROOT), "scaffolded",
            "jig (the plugin source) must classify as `scaffolded` so "
            "`workflow.py new` proceeds in the jig repo itself.",
        )


if __name__ == "__main__":
    unittest.main()
